// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbmWxgUQGXCGLL228UJopZyUy5RELVsw',
    appId: '1:957811533978:web:a9c5c4031f9418b4e81723',
    messagingSenderId: '957811533978',
    projectId: 'cathartic-gofer',
    authDomain: 'cathartic-gofer.firebaseapp.com',
    storageBucket: 'cathartic-gofer.appspot.com',
    measurementId: 'G-W8JYKG68C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVGtnmbDgPj7eDuOedWl1RNJ9gcRUG48',
    appId: '1:957811533978:android:d6002b6604ddc713e81723',
    messagingSenderId: '957811533978',
    projectId: 'cathartic-gofer',
    storageBucket: 'cathartic-gofer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgX1FjYfjH9CPo4M2TellHyq5D-n0GEEI',
    appId: '1:957811533978:ios:098bcd34c225f1dbe81723',
    messagingSenderId: '957811533978',
    projectId: 'cathartic-gofer',
    storageBucket: 'cathartic-gofer.appspot.com',
    iosClientId: '957811533978-joitanmt42ikemh4kpva37is2onnoh4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.catharticGofer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgX1FjYfjH9CPo4M2TellHyq5D-n0GEEI',
    appId: '1:957811533978:ios:aefc2811a31ca89fe81723',
    messagingSenderId: '957811533978',
    projectId: 'cathartic-gofer',
    storageBucket: 'cathartic-gofer.appspot.com',
    iosClientId: '957811533978-3dfgclmpvdscnvrcahpae33liumkvh7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.catharticGofer.RunnerTests',
  );
}
